---
title: "T-Tests"
output: html_document
date: "2026-01-23"
---


This script conducts the t-testing for the different categories.
```{r}
library(tidyverse)
library(conflicted)
library(broom) 
```


```{r}
data <- read_csv(paste0("/Users/antonioraphael/Documents/PROJECT-CLONES/",
                        "Walkenhorst-Scraping/03. Analysis/Analysis-Data/Analysis-Data.csv"))

```

```{r}
Walkenhorst_All <- data |> 
  mutate(Walkenhorst_Category = "All Products") # create all products category

Min_Categories <- data |> 
  select(Walkenhorst_Category) |> 
  group_by(Walkenhorst_Category) |> 
  summarise(Count = n()) |> # get category counts
  ungroup() |> 
  dplyr::filter(Count >= 30) # keep if there are only 30 or more obs per group


Minimum_Counts <- data |> 
  dplyr::filter(Walkenhorst_Category %in% Min_Categories$Walkenhorst_Category) # keep only when n>=30

First_Test_Data <- Walkenhorst_All |> 
  bind_rows(Minimum_Counts) #minimum counts with all products data


rm(list = ls(pattern = "Walkenhorst_All|Minimum_Counts|Min_Categories")) # environment object management
```


```{r}
First_Test_Data_Unit <- First_Test_Data |> 
  select(-c(Walkenhorst_product:kosher)) |>  # drop extra data
  select(-c(Markup)) |> # testing price per unit differences
  gather(key = "Vendor",
         value = "price_per_unit",
         -c("Walkenhorst_Category")) # long to wide for iterative testing

```


```{r}
test_function <- function(Category){
  
  
  data <- get("First_Test_Data_Unit", parent.frame()) # get data from parent env
  
  data <- data |> 
    dplyr::filter(Walkenhorst_Category == Category) # filter to category desirec

    test <- t.test(price_per_unit ~ Vendor,
                   data = data,
                   alternative = c("two.sided"),
                   mu = 0,
                   var.equal = FALSE,
                   conf.level = 0.95) # two sided test
    
    # is the price-per-unit of walkenhorst significantly different that the
    # price-per-unit of walmart
    
    test_df <- data.frame(
      Category     = Category,
      group1       = names(test$estimate)[1],
      estimate1    = test$estimate[1],
      group2       = names(test$estimate)[2],
      estimate2    = test$estimate[2],
      mean_diff    = diff(test$estimate),
      t_statistic  = as.numeric(test$statistic),
      df           = as.numeric(test$parameter),
      p_value      = test$p.value,
      conf_low     = test$conf.int[1],
      conf_high    = test$conf.int[2],
      method       = test$method,
      stringsAsFactors = FALSE
    ) # export results as data frame

    
    return(test_df) # return results data frame

}


Categories <- unique(First_Test_Data$Walkenhorst_Category) # get list of categories

dataList <- list() # empty list

dataList <- lapply(Categories, test_function) # apply test_function to categories

testDataUnit <- dataList |> 
  bind_rows() # bind rows for results

row.names(testDataUnit) <- NULL # remove row names
```

```{r}
rm(list = ls(pattern = "dataList|test_function|_Unit")) # environment/obj management

```


```{r}
First_Test_Data_Markup <- First_Test_Data |> 
  select(-c(Walkenhorst_product:kosher)) |> 
  select(-c(contains("unit_price")))  # drop unit price, testing markup
```

```{r}
test_function <- function(Category){
  
  
  data <- get("First_Test_Data_Markup", parent.frame()) # get data from global env
  
  data <- data |> 
    dplyr::filter(Walkenhorst_Category == Category) # filter to specified category 

    test <- t.test(
      data$Markup,
      alternative = "greater",  # H1: mean(markup) > 0
      mu = 0,
      conf.level = 0.95
    )
    
    # testing is Walkenhorsts percent mark up greater than 0
    
    test_df <- data.frame(
      Category     = Category,
      mean         = unname(test$estimate),
      mu_null      = test$null.value,
      t_statistic  = as.numeric(test$statistic),
      df           = as.numeric(test$parameter),
      p_value      = test$p.value,
      conf_low     = test$conf.int[1],
      conf_high    = test$conf.int[2],
      alternative  = test$alternative,
      method       = test$method,
      stringsAsFactors = FALSE
    ) # export results as data frame

    return(test_df) # return results data frame

}


Categories <- unique(First_Test_Data$Walkenhorst_Category) # get categories

dataList <- list() # empty list to save data to

dataList <- lapply(Categories, test_function) # apply test function to categories

testDataMarkup <- dataList |> 
  bind_rows() # bind to get full results data from list

row.names(testDataMarkup) <- NULL # remove pesky row names
```

```{r}
Results_Data <- testDataUnit |> 
  mutate(test_var = "price per unit") |> 
  bind_rows(testDataMarkup |> 
  mutate(test_var = "Markup")) |> 
  select(Category,
         test_var,
         everything()) # bind results data together

Results_Data$Adjusted_P_Value <- p.adjust(Results_Data$p_value, method = "BH")

# apply Benjamini–Hochberg correction

testDataMarkup <- Results_Data |> 
  dplyr::filter(test_var == "Markup") |> 
  select(where(~any(!is.na(.)))) # drop empty variables

# filter back out to results by variable tested
  
testDataUnit <- Results_Data |> 
  dplyr::filter(test_var == "price per unit") |> 
  select(where(~any(!is.na(.)))) # drop empty variables

# filter back out to results by variable tested

```


```{r}
# environment/object management
rm(list = ls(pattern = "First_Test|dataList|data|Categories|test_function|Results_Data"))

```

```{r}
write_csv(testDataUnit,
          paste0("/Users/antonioraphael/Documents/PROJECT-CLONES/",
                 "Walkenhorst-Scraping/03. Analysis/Results/Price-Per-Unit-Tests.csv")) # export

write_csv(testDataMarkup,
          paste0("/Users/antonioraphael/Documents/PROJECT-CLONES/",
                 "Walkenhorst-Scraping/03. Analysis/Results/Markup-Tests.csv")) # export

```

```{r}
First_Test_Data_Markup |> 
  group_by(Walkenhorst_Category) |> 
  summarise(Markup = mean(Markup)) |> 
  ungroup() |> 
  arrange(Markup) |> 
  mutate(Markup = round(Markup, digits = 1),
         label = paste0(Markup, "%")) |> 
  mutate(Walkenhorst_Category = str_to_title(Walkenhorst_Category)) |> 
  mutate(Walkenhorst_Category = factor(Walkenhorst_Category, 
                                       levels = Walkenhorst_Category)) |> 
  ggplot(mapping = aes(x = Walkenhorst_Category, y = Markup)) +
  geom_bar(stat = "identity")+
  labs(title = "Average Percent Mark-up (Comapred to Walmart) by Category",
       x = NULL,
       y = "Percent Mark-Up") +
  geom_text(
    aes(label = label),
    hjust = -0.1
  ) +
  ylim(0, 160) +
  theme_light()+
  coord_flip()


```
