---
title: "Initial-Plots-Raphael"
output:
  html_document:
    toc: true
    toc_depth: 3
    toc_float: true
---

```{r, echo = FALSE, message = FALSE, warning = FALSE}
library(tidyverse)
library(conflicted)
```

```{r, echo = FALSE, message = FALSE}
data <- read_csv(paste0("/Users/antonioraphael/Documents/PROJECT-CLONES/",
                        "Walkenhorst-Scraping/03. Analysis/Analysis-Data/Analysis-Data.csv"))

# 
# t_test <- read_csv(paste0("/Users/antonioraphael/Documents/PROJECT-CLONES/",
#                         "Walkenhorst-Scraping/03. Analysis/Results/Markup-Tests.csv"))
```

```{r, echo = FALSE, message = FALSE}
Walkenhorst_All <- data |> 
  mutate(Walkenhorst_Category = "All Products") # create all products category

Min_Categories <- data |> 
  select(Walkenhorst_Category) |> 
  group_by(Walkenhorst_Category) |> 
  summarise(Count = n()) |> # get category counts
  ungroup() |> 
  dplyr::filter(Count >= 30) # keep if there are only 30 or more obs per group


Minimum_Counts <- data |> 
  dplyr::filter(Walkenhorst_Category %in% Min_Categories$Walkenhorst_Category) # keep only when n>=30

First_Test_Data <- Walkenhorst_All |> 
  bind_rows(Minimum_Counts) #minimum counts with all products data


rm(list = ls(pattern = "Walkenhorst_All|Minimum_Counts|Min_Categories")) # environment object management
```


```{r, echo = FALSE, message = FALSE}
First_Test_Data_Unit <- First_Test_Data |> 
  select(-c(Walkenhorst_product:kosher)) |>  # drop extra data
  select(-c(Markup)) |> # testing price per unit differences
  gather(key = "Vendor",
         value = "price_per_unit",
         -c("Walkenhorst_Category")) # long to wide for iterative testing

```


```{r, echo = FALSE, message = FALSE}
test_function <- function(Category){
  
  
  data <- get("First_Test_Data_Unit", parent.frame()) # get data from parent env
  
  data <- data |> 
    dplyr::filter(Walkenhorst_Category == Category) # filter to category desirec

    test <- t.test(price_per_unit ~ Vendor,
                   data = data,
                   alternative = c("two.sided"),
                   mu = 0,
                   var.equal = FALSE,
                   conf.level = 0.95) # two sided test
    
    # is the price-per-unit of walkenhorst significantly different that the
    # price-per-unit of walmart
    
    test_df <- data.frame(
      Category     = Category,
      group1       = names(test$estimate)[1],
      estimate1    = test$estimate[1],
      group2       = names(test$estimate)[2],
      estimate2    = test$estimate[2],
      mean_diff    = diff(test$estimate),
      t_statistic  = as.numeric(test$statistic),
      df           = as.numeric(test$parameter),
      p_value      = test$p.value,
      conf_low     = test$conf.int[1],
      conf_high    = test$conf.int[2],
      method       = test$method,
      stringsAsFactors = FALSE
    ) # export results as data frame

    
    return(test_df) # return results data frame

}


Categories <- unique(First_Test_Data$Walkenhorst_Category) # get list of categories

dataList <- list() # empty list

dataList <- lapply(Categories, test_function) # apply test_function to categories

testDataUnit <- dataList |> 
  bind_rows() # bind rows for results

row.names(testDataUnit) <- NULL # remove row names
```

```{r, echo = FALSE, message = FALSE}
rm(list = ls(pattern = "dataList|test_function|_Unit")) # environment/obj management

```


```{r, echo = FALSE, message = FALSE}
First_Test_Data_Markup <- First_Test_Data |> 
  select(-c(Walkenhorst_product:kosher)) |> 
  select(-c(contains("unit_price")))  # drop unit price, testing markup
```

```{r, echo = FALSE, message = FALSE}
test_function <- function(Category){
  
  
  data <- get("First_Test_Data_Markup", parent.frame()) # get data from global env
  
  data <- data |> 
    dplyr::filter(Walkenhorst_Category == Category) # filter to specified category 

    test <- t.test(
      data$Markup,
      alternative = "greater",  # H1: mean(markup) > 0
      mu = 0,
      conf.level = 0.95
    )
    
    # testing is Walkenhorsts percent mark up greater than 0
    
    test_df <- data.frame(
      Category     = Category,
      mean         = unname(test$estimate),
      mu_null      = test$null.value,
      t_statistic  = as.numeric(test$statistic),
      df           = as.numeric(test$parameter),
      p_value      = test$p.value,
      conf_low     = test$conf.int[1],
      conf_high    = test$conf.int[2],
      alternative  = test$alternative,
      method       = test$method,
      stringsAsFactors = FALSE
    ) # export results as data frame

    return(test_df) # return results data frame

}


Categories <- unique(First_Test_Data$Walkenhorst_Category) # get categories

dataList <- list() # empty list to save data to

dataList <- lapply(Categories, test_function) # apply test function to categories

testDataMarkup <- dataList |> 
  bind_rows() # bind to get full results data from list

row.names(testDataMarkup) <- NULL # remove pesky row names
```

```{r, echo = FALSE, message = FALSE}
Results_Data <- testDataUnit |> 
  mutate(test_var = "price per unit") |> 
  bind_rows(testDataMarkup |> 
  mutate(test_var = "Markup")) |> 
  select(Category,
         test_var,
         everything()) # bind results data together

Results_Data$Adjusted_P_Value <- p.adjust(Results_Data$p_value, method = "BH")

# apply Benjamini–Hochberg correction

testDataMarkup <- Results_Data |> 
  dplyr::filter(test_var == "Markup") |> 
  select(where(~any(!is.na(.)))) # drop empty variables

# filter back out to results by variable tested
  
testDataUnit <- Results_Data |> 
  dplyr::filter(test_var == "price per unit") |> 
  select(where(~any(!is.na(.)))) # drop empty variables

# filter back out to results by variable tested

```


```{r, echo = FALSE, message = FALSE}
# environment/object management
rm(list = ls(pattern = "dataList|data|Categories|test_function|Results_Data"))

```

# Percent Mark-Up Bar Chart
```{r, echo = FALSE, message = FALSE, warning = FALSE}
Plot_Info <- testDataMarkup |> 
  select(Category,
         t_statistic,
         Adjusted_P_Value) |> 
  rename(Walkenhorst_Category = Category)


Markup_Plot <- First_Test_Data_Markup |> 
  group_by(Walkenhorst_Category) |> 
  summarise(Markup = mean(Markup)) |> 
  ungroup() |> 
  arrange(Markup) |> 
  mutate(Markup = round(Markup, digits = 1),
         label = paste0(Markup, "%***")) |> 
  left_join(Plot_Info,
            by = "Walkenhorst_Category") |> 
  mutate(Walkenhorst_Category = str_to_title(Walkenhorst_Category)) |> 
  mutate(Walkenhorst_Category = factor(Walkenhorst_Category, 
                                       levels = Walkenhorst_Category)) |> 
  ggplot(mapping = aes(x = Walkenhorst_Category, y = Markup)) +
  geom_bar(stat = "identity",
           fill = "#01426A")+
  labs(title = "Average Percent Mark-up by Category",
       subtitle = "Walkenhorst Mark-up over Walmart",
       x = NULL,
       y = "Percent Mark-Up",
       caption = "All Mark-Ups are significantly different than 0 at the \n1% level after Benjamini–Hochberg correction") +
  geom_text(
    aes(label = label),
    hjust = -0.1
  ) +
  # geom_text(
  # aes(label = paste0("T-Statistic: ", round(t_statistic, digits = 1)), 
  #     x = Walkenhorst_Category,
  #     y = Markup / 2),
  #     color = "white",
  # hjust = 0.5
  # ) + 
  ylim(0, 160) +
  coord_flip() +
  theme_light()+
  theme(plot.title         = element_text(vjust = 1),
        plot.subtitle      = element_text(color = "#6d6e71", hjust = 0),
        axis.text.x        = element_text(color = "black"),
        axis.text.y        = element_text(color = "#6d6e71"),
        axis.title.x       = element_text(color = "black"),
        axis.title.y       = element_text(color = "black"),
        axis.line          = element_line(size = .2),
        panel.grid         = element_line(linetype = 2, color = "#6d6e71"),
        panel.grid.major.y = element_blank(),
        panel.border       = element_blank(),
        legend.position    = "bottom",
        legend.text        = element_text(color = "#6d6e71"),
        legend.title       = element_text(color = "#6d6e71"),
        plot.caption       = element_text(color = "#6d6e71", hjust = 0)
  )

ggsave(
  filename = paste0("/Users/antonioraphael/Documents/PROJECT-CLONES/",
                    "Walkenhorst-Scraping/03. Analysis/Plots/Mark-Up-Plot.jpeg"),
  plot     = Markup_Plot,
  width    = 8,
  height   = 6,
  dpi      = 300
)
```

# Distribution Differences {.tabset}

## All Products
```{r, echo = FALSE, message = FALSE, warning = FALSE}
All_Products <- First_Test_Data |> 
  dplyr::filter(Walkenhorst_Category == "All Products") |> 
  select(Walmart_clean_unit_price, Walkenhorst_unit_price) |> 
  gather(key = "Vendor",
         value = "Value") |> 
  mutate(Vendor = recode(Vendor,
                         "Walkenhorst_unit_price"   = "Walkenhorst",
                         "Walmart_clean_unit_price" = "Walmart")) |> 
  ggplot(mapping = aes(x = Value, color = Vendor, fill = Vendor)) +
  geom_density(alpha = .7,
               color = NA)+
  scale_fill_manual(values = c("Walkenhorst" = "#01426A", 
                               "Walmart"     = "#F2CC38"))+
  labs(title = "Distribution of Product Price per Ounce, Walmart v. Walkenhorst - All Products",
       x = "Price per Ounce",
       y = NULL,
       caption = "Price-per-unit difference is significant at the 1% \nlevel after Benjamini–Hochberg correction") +
  xlim(0, 4)+
  theme_light()+
  theme(plot.title         = element_text(vjust = 1),
        plot.subtitle      = element_text(color = "#6d6e71", hjust = 0),
        axis.text.x        = element_text(color = "black"),
        axis.text.y        = element_text(color = "#6d6e71"),
        axis.title.x       = element_text(color = "black"),
        axis.title.y       = element_text(color = "black"),
        axis.line          = element_line(size = .2),
        panel.grid         = element_line(linetype = 1, color = "#6d6e71"),
        panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        panel.grid.minor.y = element_blank(),
        panel.border       = element_blank(),
        legend.position    = "bottom",
        legend.text        = element_text(color = "#6d6e71"),
        legend.title       = element_text(color = "#6d6e71"),
        plot.caption       = element_text(color = "#6d6e71", hjust = 0)
  )

ggsave(
  filename = paste0("/Users/antonioraphael/Documents/PROJECT-CLONES/",
                    "Walkenhorst-Scraping/03. Analysis/Plots/All-Products-Dist.jpeg"),
  plot     = All_Products,
  width    = 8,
  height   = 6,
  dpi      = 300
)
```

## Seafood
```{r, echo = FALSE, message = FALSE, warning = FALSE}
Seafood <- First_Test_Data |> 
  dplyr::filter(Walkenhorst_Category == "SEAFOOD") |> 
  select(Walmart_clean_unit_price, Walkenhorst_unit_price) |> 
  gather(key = "Vendor",
         value = "Value") |> 
  mutate(Vendor = recode(Vendor,
                         "Walkenhorst_unit_price"   = "Walkenhorst",
                         "Walmart_clean_unit_price" = "Walmart")) |> 
  ggplot(mapping = aes(x = Value, fill = Vendor)) +
  geom_density(alpha = .7,
               color = NA)+
  scale_fill_manual(values = c("Walkenhorst" = "#01426A", 
                               "Walmart"     = "#F2CC38"))+
  labs(title = "Distribution of Price per Ounce, Walmart v. Walkenhorst - Seafood Products",
       x = "Price per Ounce",
       y = NULL,
       caption = "Price-per-unit difference is significant at the 1% \nlevel after Benjamini–Hochberg correction") +
  theme_light()+
  theme(plot.title         = element_text(vjust = 1),
        plot.subtitle      = element_text(color = "#6d6e71", hjust = 0),
        axis.text.x        = element_text(color = "black"),
        axis.text.y        = element_text(color = "#6d6e71"),
        axis.title.x       = element_text(color = "black"),
        axis.title.y       = element_text(color = "black"),
        axis.line          = element_line(size = .2),
        panel.grid         = element_line(linetype = 1, color = "#6d6e71"),
        panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        panel.grid.minor.y = element_blank(),
        panel.border       = element_blank(),
        legend.position    = "bottom",
        legend.text        = element_text(color = "#6d6e71"),
        legend.title       = element_text(color = "#6d6e71"),
        plot.caption       = element_text(color = "#6d6e71", hjust = 0)
  )

ggsave(
  filename = paste0("/Users/antonioraphael/Documents/PROJECT-CLONES/",
                    "Walkenhorst-Scraping/03. Analysis/Plots/Seafood-Dist.jpeg"),
  plot     = Seafood,
  width    = 8,
  height   = 6,
  dpi      = 300
)
```

## Snacks
```{r, echo = FALSE, message = FALSE, warning = FALSE}
Snacks <- First_Test_Data |> 
  dplyr::filter(Walkenhorst_Category == "SNACKS") |> 
  select(Walmart_clean_unit_price, Walkenhorst_unit_price) |> 
  gather(key = "Vendor",
         value = "Value") |> 
  mutate(Vendor = recode(Vendor,
                         "Walkenhorst_unit_price"   = "Walkenhorst",
                         "Walmart_clean_unit_price" = "Walmart")) |> 
  ggplot(mapping = aes(x = Value, fill = Vendor)) +
  geom_density(alpha = .7,
               color = NA)+
  scale_fill_manual(values = c("Walkenhorst" = "#01426A", 
                               "Walmart"     = "#F2CC38"))+
  labs(title = "Distribution of Price per Ounce, Walmart v. Walkenhorst - Snack Products",
       x = "Price per Ounce",
       y = NULL,
       caption = "Price-per-unit difference is significant at the 1% \nlevel after Benjamini–Hochberg correction") +
  theme_light()+
  theme(plot.title         = element_text(vjust = 1),
        plot.subtitle      = element_text(color = "#6d6e71", hjust = 0),
        axis.text.x        = element_text(color = "black"),
        axis.text.y        = element_text(color = "#6d6e71"),
        axis.title.x       = element_text(color = "black"),
        axis.title.y       = element_text(color = "black"),
        axis.line          = element_line(size = .2),
        panel.grid         = element_line(linetype = 1, color = "#6d6e71"),
        panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        panel.grid.minor.y = element_blank(),
        panel.border       = element_blank(),
        legend.position    = "bottom",
        legend.text        = element_text(color = "#6d6e71"),
        legend.title       = element_text(color = "#6d6e71"),
        plot.caption       = element_text(color = "#6d6e71", hjust = 0)
  )

ggsave(
  filename = paste0("/Users/antonioraphael/Documents/PROJECT-CLONES/",
                    "Walkenhorst-Scraping/03. Analysis/Plots/Snacks-Dist.jpeg"),
  plot     = Snacks,
  width    = 8,
  height   = 6,
  dpi      = 300
)
```




