---
title: "T-Tests"
output: html_document
date: "2026-01-23"
---

```{r}
library(tidyverse)
library(conflicted)
library(broom) 
```


```{r}
data <- read_csv(paste0("/Users/antonioraphael/Documents/PROJECT-CLONES/",
                        "Walkenhorst-Scraping/03. Analysis/Analysis-Data/Analysis-Data.csv"))

```

```{r}
Walkenhorst_All <- data |> 
  mutate(Walkenhorst_Category = "All Products")

Min_Categories <- data |> 
  select(Walkenhorst_Category) |> 
  group_by(Walkenhorst_Category) |> 
  summarise(Count = n()) |> 
  ungroup() |> 
  dplyr::filter(Count >= 30)


Minimum_Counts <- data |> 
  dplyr::filter(Walkenhorst_Category %in% Min_Categories$Walkenhorst_Category)

First_Test_Data <- Walkenhorst_All |> 
  bind_rows(Minimum_Counts)


rm(list = ls(pattern = "Walkenhorst_All|Minimum_Counts|Min_Categories"))
```


```{r}
First_Test_Data_Unit <- First_Test_Data |> 
  select(-c(Walkenhorst_product:Walmart_unit_type)) |> 
  select(-c(Markup)) |> 
  gather(key = "Vendor",
         value = "price_per_unit",
         -c("Walkenhorst_Category"))

```


```{r}
test_function <- function(Category){
  
  
  data <- get("First_Test_Data_Unit", parent.frame())
  
  data <- data |> 
    dplyr::filter(Walkenhorst_Category == Category)

    test <- t.test(price_per_unit ~ Vendor,
                   data = data,
                   alternative = c("two.sided"),
                   mu = 0,
                   var.equal = FALSE,
                   conf.level = 0.95)
    
    test_df <- data.frame(
      Category     = Category,
      group1       = names(test$estimate)[1],
      estimate1    = test$estimate[1],
      group2       = names(test$estimate)[2],
      estimate2    = test$estimate[2],
      mean_diff    = diff(test$estimate),
      t_statistic  = as.numeric(test$statistic),
      df           = as.numeric(test$parameter),
      p_value      = test$p.value,
      conf_low     = test$conf.int[1],
      conf_high    = test$conf.int[2],
      method       = test$method,
      stringsAsFactors = FALSE
    )

    
    return(test_df)

}


Categories <- unique(First_Test_Data$Walkenhorst_Category)

dataList <- list()

dataList <- lapply(Categories, test_function)

testDataUnit <- dataList |> 
  bind_rows()

row.names(testDataUnit) <- NULL
```

```{r}
rm(list = ls(pattern = "dataList|test_function|_Unit"))

```


```{r}
First_Test_Data_Markup <- First_Test_Data |> 
  select(-c(Walkenhorst_product:Walmart_unit_type)) |> 
  select(-c(contains("unit_price"))) 
```

```{r}
test_function <- function(Category){
  
  
  data <- get("First_Test_Data_Markup", parent.frame())
  
  data <- data |> 
    dplyr::filter(Walkenhorst_Category == Category)

    test <- t.test(
      data$Markup,
      alternative = "greater",  # H1: mean(markup) > 0
      mu = 0,
      conf.level = 0.95
    )
    
    test_df <- data.frame(
      Category     = Category,
      mean         = unname(test$estimate),
      mu_null      = test$null.value,
      t_statistic  = as.numeric(test$statistic),
      df           = as.numeric(test$parameter),
      p_value      = test$p.value,
      conf_low     = test$conf.int[1],
      conf_high    = test$conf.int[2],
      alternative  = test$alternative,
      method       = test$method,
      stringsAsFactors = FALSE
    )

    return(test_df)

}


Categories <- unique(First_Test_Data$Walkenhorst_Category)

dataList <- list()

dataList <- lapply(Categories, test_function)

testDataMarkup <- dataList |> 
  bind_rows()

row.names(testDataMarkup) <- NULL
```

```{r}
First_Test_Data_Markup |> 
  group_by(Walkenhorst_Category) |> 
  summarise(Markup = mean(Markup)) |> 
  ungroup() |> 
  arrange(Markup) |> 
  mutate(Markup = round(Markup, digits = 1),
         label = paste0(Markup, "%")) |> 
  mutate(Walkenhorst_Category = str_to_title(Walkenhorst_Category)) |> 
  mutate(Walkenhorst_Category = factor(Walkenhorst_Category, 
                                       levels = Walkenhorst_Category)) |> 
  ggplot(mapping = aes(x = Walkenhorst_Category, y = Markup)) +
  geom_bar(stat = "identity")+
  labs(title = "Average Percent Mark-up (Comapred to Walmart) by Category",
       x = NULL,
       y = "Percent Mark-Up") +
  geom_text(
    aes(label = label),
    hjust = -0.1
  ) +
  ylim(0, 160) +
  theme_light()+
  coord_flip()


```
