---
title: "Combining-Scraped-Data"
output: html_document
date: "2026-01-14"
---


This script combines all JSON file containing scraped products data, cleans product text strings, standardizes the price-per-unit ratio, and aggregates the file to a format more conducive to fuzzy matching.
```{r}
library(tidyverse)
library(jsonlite)

```

```{r}
files <- list.files(
  path = "~/Documents/PROJECT-CLONES/Walkenhorst-Scraping/01. Scraping/Scraped-JSON-Files/",
  pattern = "\\.json$", # get file paths and files for all json files
  full.names = TRUE
)

df <- bind_rows(lapply(files, function(f) {
  fromJSON(f, flatten = TRUE) |> # read all files in at once
    mutate(source_file = basename(f))
}))

```

```{r}
Products_Categories <- df |> 
  select(`__typename`,
         name,
         catalogProductType,
         price,
         priceInfo.linePrice,
         priceInfo.linePriceDisplay,
         priceInfo.unitPrice,
         source_file) |> # select relevant variables
  dplyr::filter(`__typename` == "Product") |> # select product data only not other website data
  select(-c(`__typename`)) |> # drop type
  select(source_file, everything()) |>  # reorder
  distinct() # de-duplicate any repeat products

Products_Only <- Products_Categories |> 
  select(-c(source_file, 
            priceInfo.linePriceDisplay)) |> # drop category variables
  distinct() # de-duplicate any repeat products
```


```{r}
Products_Categories <- Products_Categories |> 
  dplyr::filter(!str_detect(name, "Great Value")) |> # drop walmart brand stuff
  mutate(name =  str_remove_all(
    name,
    regex(
      "\\b(\\d+\\s*-?\\s*(pack|cans?)|pack\\s+of\\s+\\d+)\\b",
      ignore_case = TRUE
    )),
    name = gsub("()", "", name, fixed = TRUE),
    name = trimws(name),
    name = str_remove_all(
    name,
    regex(
      ",\\s*\\d+(\\.\\d+)?\\s*oz.*$",
      ignore_case = TRUE
    )
  ),
    name = str_remove_all(
      name,
      regex(
        "\\s*\\d+(\\.\\d+)?\\s*oz.*$",
        ignore_case = TRUE
      )),
    name = str_remove_all(
      name,
      regex(
        ",\\s*\\d+(\\.\\d+)?\\s*fl\\.?\\s*oz.*$",
        ignore_case = TRUE
      )),
    name = str_remove_all(
      name,
      regex(
        "\\s*\\d+\\s*fl\\.?\\s*oz.*$",
        ignore_case = TRUE
      )),
    name = str_remove_all(
      name,
      regex(
        ",?\\s*\\d+\\s*-\\s*oz\\.?\\s*.*$",
        ignore_case = TRUE
      )),
    name = str_remove_all(
      name,
      regex(
        ",?\\s*\\d+(\\.\\d+)?\\s*ounce.*$",
        ignore_case = TRUE
      )),
    name = str_remove_all(
      name,
      regex(
        ",?\\s*\\d+\\s*(count|ct)\\.?\\s*.*$",
        ignore_case = TRUE
      )),
    name = str_remove_all(
      name,
      regex(
        "\\b\\d+\\s*g\\s*protein\\b",
        ignore_case = TRUE
      )),
    name = str_remove_all(
      name,
      regex(
        "(?i)\\b(\\d+(?:\\.\\d+)?\\s*(?:l|liter|liters|qt|gallon|lb)\\b(?:\\s*bottle|\\s*bag)?|#\\s*(?:l|liter|liters|gallon|lb)\\b(?:\\s*bottle|\\s*bag)?)",
        ignore_case = TRUE
      )),
    name = str_remove_all(
      name,
      ", , Bottle")
   ) 

# the above formats the strings to remove quantities from the product title, this will allow us to aggregate the product unit price and facilitate a better fuzzy join
```


```{r}
# The following standardizes all the unit prices for things expressed in weights

Cleaned_Unit_Prices <- Products_Categories |> 
  mutate(unit_price = priceInfo.unitPrice) |>  # rename
  select(unit_price) |> 
  distinct() |> # distinct obs, merge back later
  mutate(unit_price_original = unit_price) |> 
  select(unit_price_original, unit_price) |> 
  mutate(weights = str_detect(unit_price, "oz|lb|ounces|/gl|¢/l")) |> # filter to all weight (non-count) obs
  dplyr::filter(weights == TRUE) |> 
  mutate(cents_oz = str_detect(unit_price, "¢/oz|¢/fl oz|¢/ounces"), # detect format
         cents_lb = str_detect(unit_price, "¢/lb"),# detect format
         dollars_gallon = str_detect(unit_price, "/gl"),# detect format
         liter_detect = str_detect(unit_price, "^\\d+(?:\\.\\d+)?\\s*¢/l$"),# detect format
         unit_price = str_remove_all(unit_price, " ¢/oz"), # strip text formatting
         unit_price = str_remove_all(unit_price, " ¢/fl oz"), # strip text formatting
         unit_price = str_remove_all(unit_price, " ¢/lb"), # strip text formatting
         unit_price = str_remove_all(unit_price, " ¢/l"), # strip text formatting
         unit_price = str_remove_all(unit_price, "(\\$|/gl)"), # strip text formatting
         clean_unit_price = case_when(cents_oz == TRUE ~ as.numeric(unit_price)/100, # cents/ounce to dollars/ounce
                                      cents_lb == TRUE ~ (as.numeric(unit_price)/16)/100, #cents/pound to dollars/ounce
                                      dollars_gallon == TRUE ~ (as.numeric(unit_price)/128), # dollars/gallor to dollars ounce
                                      liter_detect == TRUE ~ (as.numeric(unit_price)/33.8140227), #dollars/liters to dollars/ounce
                                      TRUE ~ NA_integer_)
         ) |> 
  select(-c(weights:liter_detect)) |> 
  mutate(pound = str_detect(unit_price, "/lb"),
         unit_price = str_remove_all(unit_price, "/oz|/fl oz|/lb"),
         unit_price = gsub("$", "", unit_price, fixed = TRUE),
         clean_unit_price_2 = case_when(pound == TRUE ~ as.numeric(unit_price)/16,
                                        TRUE ~ NA_integer_)) |>  # additional cleaning, same method
  mutate(clean_unit_price = coalesce(clean_unit_price,
                                     clean_unit_price_2), # coalesce for clean variable
         unit_price = as.numeric(unit_price),
         clean_unit_price = coalesce(clean_unit_price,
                                     unit_price)) |> 
  select(-c(unit_price,
            clean_unit_price_2,
            pound)) |> # drop extrac
  rename(unit_price = unit_price_original) |> 
  mutate(unit_type = "price per ounce") # type of price per unit

```

```{r}
# need to repeat the same thing with price per count

Clean_Unit_Prices_Count <- Products_Categories |> 
  mutate(unit_price = priceInfo.unitPrice) |> 
  select(unit_price) |> 
  distinct() |> 
  mutate(unit_price_original = unit_price) |> 
  select(unit_price_original, unit_price) |> 
  mutate(weights = str_detect(unit_price, "oz|lb|ounces|/gl|¢/l")) |> #weight detect
  dplyr::filter(weights == FALSE)  |> 
  dplyr::filter(unit_price_original != "") |> 
  select(-c(weights)) |> 
  mutate(cents_counts = str_detect(unit_price, "¢/count"), # detect cents count
         cents_each = str_detect(unit_price, "¢/ea"), # detect cents each
         dollars_each = str_detect(unit_price, "\\$\\d+(?:\\.\\d{2})?/ea"), # detect dollars each
         hundred = str_detect(unit_price, "/100 ct"), # detect price per 100
         dollars_count = str_detect(unit_price, "\\$\\d+(?:\\.\\d{2})?/count")) |>  # format
  mutate(clean_unit_price = case_when(cents_counts == TRUE ~ as.numeric(str_remove(unit_price, "¢/count"))/100, # dollars per count
                                      cents_each == TRUE ~ as.numeric(str_remove(unit_price, "¢/ea"))/100, # dollars each
                                      dollars_each == TRUE ~ as.numeric(gsub("(\\$|/ea)", "", unit_price)), # remove fomrmatting as numeric
                                      hundred == TRUE ~ as.numeric(gsub("(\\$|/\\d+\\s*ct)", "", unit_price))/100, # divide by 100
                                      dollars_count == TRUE ~ as.numeric(gsub("(\\$|/count)", "", unit_price)), # standardize
                                      TRUE ~ NA_integer_)) |> 
  select(-c(unit_price,cents_counts, cents_each, dollars_each, hundred, dollars_count)) |> 
  rename(unit_price = unit_price_original) |> 
  mutate(unit_type = "price per count")

  

```

```{r}
Cleaned_Unit_Prices <- Cleaned_Unit_Prices |> 
  bind_rows(Clean_Unit_Prices_Count) # cleaned per unit data

```

```{r}
Products_Categories <- Products_Categories |> 
  mutate(unit_price = priceInfo.unitPrice) |> 
  left_join(Cleaned_Unit_Prices,
            by = "unit_price") # merge clean per unit data to products data
```

```{r}
rm(list = ls(pattern = "Clean")) # enrivornment/object management

```

```{r}
To_Aggregate <- Products_Categories |> 
  dplyr::filter(!is.na(clean_unit_price)) |> 
  mutate(name = str_remove(name, "[^A-Za-z]+$"), # remove non-characters
         name = str_remove(name, "\\.+$"), 
         name = trimws(name, which = "both", whitespace = " "), # remove extra white space
         name = trimws(name, which = "both", whitespace = "[\t\r\n]"), # remove extra special white space
         ) |> 
  arrange(source_file) |> # arrange by group
  group_by(source_file) |> 
  arrange(name, .by_group = TRUE) |>  # arranve by product
  ungroup() |> 
  select(-c(catalogProductType:unit_price)) |>  # drop extra variables
  group_by(source_file, name, unit_type) |>  # group by 
  summarise(clean_unit_price = mean(clean_unit_price)) |> # take mean of price per unit 
  ungroup()  # ungroup

Products_Categories <- Products_Categories |> 
  dplyr::filter(is.na(clean_unit_price)) |>  
  select(-c(catalogProductType:priceInfo.unitPrice)) |> # drop extra variables
  select(-c(clean_unit_price)) |>  
  bind_rows(To_Aggregate) # bind aggreagted data

# 15674
```

```{r}
# export
write_csv(Products_Categories,
          "~/Documents/PROJECT-CLONES/Walkenhorst-Scraping/01. Scraping/Scraped-JSON-Files/Full-Products-Data/Products_Categories.csv")

write_csv(Products_Only,
          "~/Documents/PROJECT-CLONES/Walkenhorst-Scraping/01. Scraping/Scraped-JSON-Files/Full-Products-Data/Products_Only.csv")
```

